// src/components/GameOver.tsx
import type { Card, Player } from '../types'
import { Scoreboard } from './Scoreboard'

type Props = {
  players: Player[]
  scores: Record<string, number>
  pointsHistory: Record<string, number[]>
  cardHistory: Record<string, Card[]>
  winner: Player
  onRestart: () => void
}

export function GameOver({ players, scores, pointsHistory, cardHistory, winner, onRestart }: Props) {
  return (
    <div className="mx-auto flex min-h-svh max-w-sm flex-col gap-6 p-4">
      <h1 className="text-center text-3xl font-bold">Tutto Counter</h1>
      <p className="text-center">
        <span className="rounded border-2 border-yellow-400 bg-yellow-300 px-3 py-1 text-xl font-medium text-black">
          {winner.name} wins!
        </span>
      </p>

      <Scoreboard
        players={players}
        scores={scores}
        pointsHistory={pointsHistory}
        cardHistory={cardHistory}
      />

      <button
        type="button"
        onClick={onRestart}
        className="mt-auto rounded bg-purple-600 py-3 text-lg font-medium text-white"
      >
        play again
      </button>
    </div>
  )
}

// src/components/screens/GameOver.vue
<script lang="ts" setup>
import type { Card, Player } from "../../types.ts";
import Scoreboard from "./Scoreboard.vue";

defineProps<{
  players: Player[];
  scores: Record<string, number>;
  pointsHistory: Record<string, number[]>;
  cardHistory: Record<string, Card[]>;
  winner: Player;
  onRestart: () => void;
}>();
</script>

<template>
  <div>
    <h1>Tutto Counter</h1>
    <p>
      Game Over! <strong>{{ winner.name }}</strong> wins!
    </p>
    <Scoreboard
      :players="players"
      :scores="scores"
      :pointsHistory="pointsHistory"
      :cardHistory="cardHistory"
    />
    <button @click="onRestart">Restart Game</button>
  </div>
</template>
