// src/components/TurnScreen.tsx
import { useState } from 'react'
import type { Card, Player } from '../types'
import { Keypad } from './Keypad'
import { Scoreboard } from './Scoreboard'

const BONUS_CARDS = [
  'bonus-100',
  'bonus-200',
  'bonus-300',
  'bonus-400',
  'bonus-500',
  'bonus-600',
] as const satisfies readonly Exclude<Card, null>[]

type Props = {
  players: Player[]
  scores: Record<string, number>
  pointsHistory: Record<string, number[]>
  cardHistory: Record<string, Card[]>
  activePlayerIndex: number
  isFinalRound: boolean
  onSkip: () => void
  onComplete: (points: number, card: Card, reachedTutto: boolean) => void
}

export function TurnScreen({
  players,
  scores,
  pointsHistory,
  cardHistory,
  activePlayerIndex,
  isFinalRound,
  onSkip,
  onComplete,
}: Props) {
  const [tab, setTab] = useState<'turn' | 'scoreboard'>('turn')
  const [digits, setDigits] = useState('')
  const [card, setCard] = useState<Card>(null)
  const [step, setStep] = useState<'entry' | 'confirm'>('entry')

  const activePlayer = players[activePlayerIndex]

  // Drawing swap-1000, street, or insta-win asks a yes/no question right away.
  function chooseCard(value: Exclude<Card, 'firework' | null>) {
    setCard(value)
    setStep('confirm')
  }

  // Firework and the bonus cards ask nothing — they just tag the turn while
  // entry continues normally, so pressing one again untags it.
  function toggleTag(value: Exclude<Card, null>) {
    setCard((prev) => (prev === value ? null : value))
  }

  function submitEntry() {
    if (digits === '') return
    onComplete(Number(digits), card, false)
  }

  return (
    <div className="flex h-dvh w-dvw flex-col gap-2 p-4">
      <h1 className="text-center text-2xl font-bold">Tutto Counter</h1>

      {isFinalRound && (
        <p className="text-center text-sm font-medium text-purple-600">
          final round – highest score wins
        </p>
      )}

      <div className="flex gap-2 text-sm">
        <button
          type="button"
          onClick={() => setTab('turn')}
          className={`flex-1 rounded border py-2 ${tab === 'turn' ? 'bg-purple-600 text-white' : ''}`}
        >
          turn
        </button>
        <button
          type="button"
          onClick={() => setTab('scoreboard')}
          className={`flex-1 rounded border py-2 ${tab === 'scoreboard' ? 'bg-purple-600 text-white' : ''}`}
        >
          scoreboard
        </button>
      </div>

      {tab === 'scoreboard' && (
        <Scoreboard
          players={players}
          scores={scores}
          pointsHistory={pointsHistory}
          cardHistory={cardHistory}
          activePlayerId={activePlayer.id}
        />
      )}

      {tab === 'turn' && step === 'entry' && (
        <>
          <div className='flex flex-col justify-between flex-1'>

            <p className="text-center text-lg">{activePlayer.name}'s turn</p>

            <button
              type="button"
              onClick={() => setDigits('')}
              aria-label="Clear entered points"
              className="rounded font-bold text-4xl py-3 text-center"
            >
              {digits || '0'}
            </button>
            {/* card space */}
            <div className='flex flex-col gap-2'>
              <div className="flex gap-1">
                <button type="button" onClick={onSkip} className="text-sm flex-1 rounded border py-2">
                  skip
                </button>
                <button
                  type="button"
                  onClick={() => toggleTag('firework')}
                  className={`flex-1 text-sm rounded border py-2 ${card === 'firework' ? 'bg-purple-600 text-white' : ''}`}
                >
                  firework
                </button>
              </div>
              <div className="flex gap-1 text-sm">
                <button
                  type="button"
                  onClick={() => chooseCard('swap-1000')}
                  className="flex-1 rounded border py-2 text-sm"
                >
                  +-1000
                </button>
                <button
                  type="button"
                  onClick={() => chooseCard('street')}
                  className="flex-1 rounded border py-2 text-sm"
                >
                  street
                </button>
                <button
                  type="button"
                  onClick={() => chooseCard('insta-win')}
                  className="flex-1 rounded border py-2"
                >
                  insta win
                </button>
              </div>
              <div className="flex flex-1 gap-1">
                {BONUS_CARDS.map((value) => (
                  <button
                    key={value}
                    type="button"
                    onClick={() => toggleTag(value)}
                    className={`flex-1 text-sm rounded border py-2 ${card === value ? 'bg-purple-600 text-white' : ''}`}
                  >
                    +{value.replace('bonus-', '')}
                  </button>
                ))}
              </div>
            </div>

            <Keypad
              onDigit={(digit) => setDigits((prev) => prev + digit)}
              onSubmit={submitEntry}
              submitDisabled={digits === ''}
            />
          </div>
        </>
      )}

      {tab === 'turn' && step === 'confirm' && (
        <>
          <p className="text-center text-lg">{activePlayer.name}'s turn</p>
          <p className="text-center font-medium">
            {card === 'insta-win'
              ? 'reached tutto twice in a row?'
              : card === 'street'
                ? 'reached street?'
                : 'reached tutto?'}
          </p>

          <div className="flex gap-3">
            <button
              type="button"
              onClick={() => onComplete(0, card, true)}
              className="flex-1 rounded border py-3"
            >
              yes
            </button>
            <button
              type="button"
              onClick={() => onComplete(0, card, false)}
              className="flex-1 rounded border py-3"
            >
              no
            </button>
          </div>
        </>
      )}
    </div>
  )
}

// src/components/screens/TurnScreen.vue
<script lang="ts" setup>
import { computed, ref } from "vue";
import type { Card, Player } from "../../types.ts";
import Keypad from "../ui_elements/Keypad.vue";
import Scoreboard from "./Scoreboard.vue";

const props = defineProps<{
  players: Player[];
  scores: Record<string, number>;
  pointsHistory: Record<string, number[]>;
  cardHistory: Record<string, Card[]>;
  activePlayerIndex: number;
  isFinalRound: boolean;
  onSkip: () => void;
  onComplete: (points: number, card: Card, reachedTutto: boolean) => void;
}>();

const BONUS_CARDS = [
  "bonus-100",
  "bonus-200",
  "bonus-300",
  "bonus-400",
  "bonus-500",
  "bonus-600",
] as const satisfies readonly Exclude<Card, null>[];

const tab = ref<"turn" | "scoreboard">("turn");
const digits = ref("");
const card = ref<Card>(null);
const step = ref<"entry" | "confirm">("entry");
const activePlayer = computed(() => props.players[props.activePlayerIndex]);

function setDigits(value: string) {
  digits.value = value;
}

function appendDigit(digit: string) {
  digits.value += digit;
}

function chooseCard(value: Exclude<Card, "firework" | null>) {
  card.value = value;
  step.value = "confirm";
}

function toggleTag(value: Exclude<Card, null>) {
  card.value = card.value === value ? null : value;
}

function submitEntry() {
  if (digits.value === "") return;
  props.onComplete(Number(digits.value), card.value, false);
}
</script>

<template>
  <section class="flex flex-col w-full h-full">
    <p v-if="props.isFinalRound" class="final-round">
      final round – highest score wins
    </p>

    <div class="bg-slate-200 flex gap-2 rounded-full">
      <button
        class="flex-1 cursor-pointer rounded-full"
        type="button"
        :class="{ 'bg-slate-400': tab === 'turn' }"
        @click="tab = 'turn'"
      >
        turn
      </button>
      <button
        class="flex-1 cursor-pointer rounded-full"
        type="button"
        :class="{ 'bg-slate-400': tab === 'scoreboard' }"
        @click="tab = 'scoreboard'"
      >
        scoreboard
      </button>
    </div>

    <Scoreboard
      v-if="tab === 'scoreboard'"
      :players="props.players"
      :scores="props.scores"
      :pointsHistory="props.pointsHistory"
      :cardHistory="props.cardHistory"
      :activePlayerId="activePlayer?.id"
    />

    <div v-else-if="step === 'entry'" class="flex flex-col">
      <!-- turn and score area -->
      <div class="flex flex-col items-center py-4">
        <p class="text-4xl font-bold py-4">{{ activePlayer?.name }}'s turn</p>
        <button
          type="button"
          class="border rounded w-full h-12 text-2xl"
          @click="setDigits('')"
        >
          {{ digits || "0" }}
        </button>
      </div>

      <!-- cards stack -->
      <div id="card-stack" class="py-8 flex gap-2 flex-col">
        <div class="flex flex-row gap-1">
          <button
            type="button"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="props.onSkip"
          >
            skip
          </button>
          <button
            type="button"
            :class="{ 'bg-slate-400': card === 'firework' }"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="toggleTag('firework')"
          >
            firework
          </button>
          <button
            type="button"
            :class="{ 'bg-slate-400': card === 'double-points' }"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="toggleTag('double-points')"
          >
            points x2
          </button>
        </div>

        <div class="flex flex-row gap-1">
          <button
            type="button"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="chooseCard('swap-1000')"
          >
            +-1000
          </button>
          <button
            type="button"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="chooseCard('street')"
          >
            street
          </button>
          <button
            type="button"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="chooseCard('insta-win')"
          >
            insta win
          </button>
        </div>

        <div class="flex flex-row gap-1">
          <button
            v-for="value in BONUS_CARDS"
            :key="value"
            type="button"
            :class="{ 'bg-slate-400': card === value }"
            class="text-sm rounded-full px-2 py-1 bg-slate-200 flex-1"
            @click="toggleTag(value)"
          >
            +{{ value.replace("bonus-", "") }}
          </button>
        </div>
      </div>

      <Keypad
        :onDigit="appendDigit"
        :onSubmit="submitEntry"
        :submitDisabled="digits === ''"
      />
    </div>

    <div v-else class="confirm-panel">
      <p class="turn-label">{{ activePlayer?.name }}'s turn</p>
      <p class="confirm-question">
        {{
          card === "insta-win"
            ? "reached tutto twice in a row?"
            : card === "street"
              ? "reached street?"
              : "reached tutto?"
        }}
      </p>

      <div class="confirm-actions">
        <button
          type="button"
          class="action-button"
          @click="props.onComplete(0, card, true)"
        >
          yes
        </button>
        <button
          type="button"
          class="action-button"
          @click="props.onComplete(0, card, false)"
        >
          no
        </button>
      </div>
    </div>
  </section>
</template>
