// src/components/PlayerSetup.vue
<script lang="ts" setup>
import type { Player } from "../types";
const MIN_PLAYERS = 2;
const MAX_PLAYERS = 10;

defineProps<{
  players: Player[];
  addPlayer: () => void;
  removePlayer: (id: string) => void;
  renamePlayer: (id: string, newName: string) => void;
  movePlayer: (id: string, direction: "up" | "down") => void;
  onStart: () => void;
}>();
</script>

<template>
  <div class="player-setup">
    <h1>Tutto Counter</h1>
    <ul class="player-list">
      <li v-for="player in players" :key="player.id">
        <div class="order-buttons">
          <button @click="movePlayer(player.id, 'up')">U</button>
          <button @click="movePlayer(player.id, 'down')">D</button>
        </div>
        <input
          type="text"
          v-model="player.name"
          @input="renamePlayer(player.id, player.name)"
          placeholder="Enter player name"
        />
        <button
          @click="removePlayer(player.id)"
          :disabled="players.length <= MIN_PLAYERS"
        >
          Remove
        </button>
      </li>
      <button v-if="players.length < MAX_PLAYERS" @click="addPlayer">
        Add Player
      </button>
    </ul>
    <div class="actionButtons">
      <button @click="onStart" :disabled="players.length < MIN_PLAYERS">
        Start Game
      </button>
    </div>
  </div>
</template>

<style scoped>
.order-buttons {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
  button {
    font-size: 0.825rem;
    flex: 1;
  }
}
.actionButtons {
  display: flex;
  gap: 0.5rem;
  padding: 1rem;
}
.player-setup {
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
}
h1 {
  padding: 1rem;
}
.player-list {
  list-style-type: none;
  padding: 0;
  margin: 0;
  gap: 0.5rem;
  flex: 1;
}
input[type="text"] {
  height: 3rem;
  font-size: 1rem;
  border: solid 1px hsl(0, 0%, 40%);
  background-color: #fff;
  border-radius: 0.5rem;
  padding-left: 0.5rem;
  padding-right: 0.5rem;
}
button {
  height: 3rem;
  font-size: 1rem;
  border: solid 1px hsl(0, 0%, 40%);
  background-color: #fff;
  border-radius: 0.5rem;
  padding-left: 0.5rem;
  padding-right: 0.5rem;
}
li {
  display: flex;
  flex-direction: row;
  gap: 0.25rem;
}
ul {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
  flex: 1;
}
</style>

// src/components/PlayerSetup.tsx
import type { Player } from '../types'

const MIN_PLAYERS = 2
const MAX_PLAYERS = 10

type Props = {
  players: Player[]
  onAdd: () => void
  onRemove: (id: string) => void
  onRename: (id: string, name: string) => void
  onMove: (id: string, direction: 'up' | 'down') => void
  onStart: () => void
}

export function PlayerSetup({ players, onAdd, onRemove, onRename, onMove, onStart }: Props) {
  return (
    <div className="mx-auto flex min-h-svh max-w-sm flex-col gap-6 p-4">
      <h1 className="text-center text-3xl font-bold">Tutto Counter</h1>

      <ul className="flex flex-col gap-3">
        {players.map((player, index) => (
          <li key={player.id} className="flex items-center gap-2">
            <div className="flex flex-col gap-1">
              <button
                type="button"
                onClick={() => onMove(player.id, 'up')}
                disabled={index === 0}
                aria-label="Move player up"
                className="rounded border px-2 disabled:opacity-30"
              >
                ↑
              </button>
              <button
                type="button"
                onClick={() => onMove(player.id, 'down')}
                disabled={index === players.length - 1}
                aria-label="Move player down"
                className="rounded border px-2 disabled:opacity-30"
              >
                ↓
              </button>
            </div>

            <input
              type="text"
              value={player.name}
              onChange={(event) => onRename(player.id, event.target.value)}
              placeholder={`Player ${index + 1}`}
              className="min-w-0 flex-1 rounded border px-3 py-2"
            />

            <button
              type="button"
              onClick={() => onRemove(player.id)}
              disabled={players.length <= MIN_PLAYERS}
              className="rounded border px-3 py-2 disabled:opacity-30"
            >
              del
            </button>
          </li>
        ))}
      </ul>

      <button
        type="button"
        onClick={onAdd}
        disabled={players.length >= MAX_PLAYERS}
        aria-label="Add player"
        className="self-center rounded-full border w-10 h-10 text-xl leading-none disabled:opacity-30"
      >
        +
      </button>

      <p className="text-center text-sm text-gray-500 dark:text-gray-400">
        To get the best experience, order the players like you are sitting at the table.
      </p>

      <button
        type="button"
        onClick={onStart}
        className="mt-auto rounded bg-purple-600 py-3 text-lg font-medium text-white"
      >
        start round
      </button>
    </div>
  )
}
