// src/App.tsx
import { useState } from 'react'
import { nanoid } from 'nanoid'
import type { GameState, Player } from './types'
import { applyTurn, createGame } from './gameLogic'
import { PlayerSetup } from './components/PlayerSetup'
import { TurnScreen } from './components/TurnScreen'
import { GameOver } from './components/GameOver'

function createPlayer(): Player {
  return { id: nanoid(), name: '' }
}

function App() {
  const [players, setPlayers] = useState<Player[]>([createPlayer(), createPlayer()])
  const [game, setGame] = useState<GameState | null>(null)

  function addPlayer() {
    setPlayers((prev) => (prev.length >= 10 ? prev : [...prev, createPlayer()]))
  }

  function removePlayer(id: string) {
    setPlayers((prev) => (prev.length <= 2 ? prev : prev.filter((player) => player.id !== id)))
  }

  function renamePlayer(id: string, name: string) {
    setPlayers((prev) => prev.map((player) => (player.id === id ? { ...player, name } : player)))
  }

  function movePlayer(id: string, direction: 'up' | 'down') {
    setPlayers((prev) => {
      const index = prev.findIndex((player) => player.id === id)
      const swapWith = direction === 'up' ? index - 1 : index + 1
      if (swapWith < 0 || swapWith >= prev.length) return prev

      const next = [...prev]
      ;[next[index], next[swapWith]] = [next[swapWith], next[index]]
      return next
    })
  }

  function startRound() {
    const namedPlayers = players.map((player, index) => ({
      ...player,
      name: player.name.trim() || `Player ${index + 1}`,
    }))
    setGame(createGame(namedPlayers))
  }

  function restart() {
    setGame(null)
  }

  if (!game) {
    return (
      <PlayerSetup
        players={players}
        onAdd={addPlayer}
        onRemove={removePlayer}
        onRename={renamePlayer}
        onMove={movePlayer}
        onStart={startRound}
      />
    )
  }

  if (game.winner) {
    return (
      <GameOver
        players={game.players}
        scores={game.scores}
        pointsHistory={game.pointsHistory}
        cardHistory={game.cardHistory}
        winner={game.winner}
        onRestart={restart}
      />
    )
  }

  return (
    <TurnScreen
      key={game.turnNumber}
      players={game.players}
      scores={game.scores}
      pointsHistory={game.pointsHistory}
      cardHistory={game.cardHistory}
      activePlayerIndex={game.activePlayerIndex}
      isFinalRound={game.finalRoundTriggeredBy !== null}
      onSkip={() => setGame((current) => applyTurn(current!, 0, null, false))}
      onComplete={(points, card, reachedTutto) =>
        setGame((current) => applyTurn(current!, points, card, reachedTutto))
      }
    />
  )
}

export default App

// src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { nanoid } from "nanoid";
import type { GameState, Player } from "./types";
import { applyTurn, createGame } from "./gameLogic";
import PlayerSetup from "./components/PlayerSetup.vue";
import GameOver from "./components/GameOver.vue";
import TurnScreen from "./components/TurnScreen.vue";

const players = ref<Player[]>([
  { id: nanoid(), name: "Franzi" },
  { id: nanoid(), name: "Jasper" },
]);
const game = ref<GameState | null>(null);

function createPlayer(): Player {
  return { id: nanoid(), name: "" };
}

function addPlayer() {
  if (players.value.length >= 10) {
    return;
  }
  players.value = [...players.value, createPlayer()];
}

function removePlayer(id: string) {
  if (players.value.length <= 2) {
    return;
  }
  players.value = players.value.filter((player) => player.id !== id);
}

function renamePlayer(id: string, newName: string) {
  players.value = players.value.map((player) =>
    player.id === id ? { ...player, name: newName } : player,
  );
}

//Todo: moveplayer function
// function movePlayer(id: string, direction: "up" | "down") {
//   const index = players.value.findIndex((player) => player.id === id);
//   if (index === -1) return;
//   const newIndex = direction === "up" ? index - 1 : index +1;
//   if (newIndex < 0 || newIndex >= players.value.length) return;
//   const newPlayers = [...players.value];
// }

function startRound() {
  const namedPlayers = players.value.map((player, index) => ({
    ...player,
    name: player.name.trim() || `Player ${index + 1}`,
  }));
  game.value = createGame(namedPlayers);
}

function restart() {
  game.value = null;
}
</script>

<template>
  <PlayerSetup
    v-if="!game"
    :players="players"
    :addPlayer="addPlayer"
    :removePlayer="removePlayer"
    :renamePlayer="renamePlayer"
    :onStart="startRound"
  />
  <GameOver
    v-else-if="game.winner"
    :players="game.players"
    :scores="game.scores"
    :pointsHistory="game.pointsHistory"
    :cardHistory="game.cardHistory"
    :winner="game.winner"
    :onRestart="restart"
  />

  <TurnScreen
    v-else
    :key="game.turnNumber"
    :players="game.players"
    :scores="game.scores"
    :pointsHistory="game.pointsHistory"
    :cardHistory="game.cardHistory"
    :activePlayerIndex="game.activePlayerIndex"
    :isFinalRound="game.finalRoundTriggeredBy !== null"
    :onSkip="
      () => {
        game = applyTurn(game!, 0, null, true);
      }
    "
    :onComplete="
      (points, card, isSkip) => {
        game = applyTurn(game!, points, card, isSkip);
      }
    "
  />
</template>

<style scoped></style>
